font_family        family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Light
bold_font          family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Light
italic_font        family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-LightItalic
bold_italic_font   family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-LightItalic
# font_family      ComicShannsMono Nerd Font

font_size 20.0

disable_ligatures never
