font_family        family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Light
bold_font          family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-Light
italic_font        family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-LightItalic
bold_italic_font   family='Maple Mono NF CN' postscript_name=MapleMono-NF-CN-LightItalic

# * 中文字符，LXGW
symbol_map U+2E80-U+2EFF,U+2F00-U+2FDF,U+3000-U+303F,U+31C0-U+31EF,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FF00-U+FFEF LXGW WenKai Mono
# font_family      ComicShannsMono Nerd Font

font_size 20.0

disable_ligatures never
