# 左右分屏（左 / 右）
map cmd+d launch --location=hsplit --cwd=current

map cmd+w send_key cmd+w
map shift+cmd+w close_window
map ctrl+tab send_key ctrl+tab
map cmd+f no_op
# * Fuck Apple, Fuck MacOS
map cmd+h no_op
map cmd+0 send_key cmd+0

map cmd+h neighboring_window left
map cmd+l neighboring_window right
map cmd+j neighboring_window bottom
map cmd+k neighboring_window top

# * open directly http://localhost:3000
# * default key map => ctrl + shift + e
map cmd+o open_url http://localhost:3000

# 禁用新窗口快捷键
map cmd+n no_op
map shift+cmd+n launch --type=os-window --cwd=current
map ctrl+shift+n no_op

# * 主题切换 (light/dark)
map cmd+ctrl+t remote_control_script ~/.config/kitty/toggle-theme.sh
map cmd+ctrl+r remote_control_script ~/.config/kitty/reload-theme.sh

# ctrl + ; 切换输入法~
map ctrl+; discard_event
