"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold #2E7DE9)$directory\
$git_branch\
$git_status\
\n[╰─ ](bold #2E7DE9)
"""

[directory]
format = "[ $path ]($style)"
style = "bold #007197"
truncation_length = 3
truncation_symbol = "…/"

#[git_branch]
#symbol = "TvT"
#format = '[$symbol \($branch\) ]($style)'
#style = 'cyan'

[git_branch]
symbol = "TvT"
format = '[[$symbol](#9854F1) \([$branch](#7847BD)\) ]($style)'
style = 'bold #2E7DE9'

[git_status]
conflicted = "|🤡 conflicted"
ahead = " ↑🎉 ahead"
behind = " ↓😡 behind"
diverged  = "|🤬 diverged"
# for space
modified  = "|🥹  modified"
staged    = "|😋 staged"
untracked = "|😅 untracked"
# stashed = "|🤓stashed"
renamed = "|🫣  renamed"
deleted = "|🤮 deleted"

format = '([$all_status$ahead_behind]($style)) '
style = "bold #587539"
