"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold #7AA2F7)$directory\
$git_branch\
$git_status\
\n[╰─ ](bold #7AA2F7)
"""

[directory]
format = "[ $path ]($style)"
style = "bold #7DCFFF"
truncation_length = 3
truncation_symbol = "…/"

#[git_branch]
#symbol = "TvT"
#format = '[$symbol \($branch\) ]($style)'
#style = 'cyan'

[git_branch]
symbol = "TvT"
format = '[[$symbol](#BB9AF7) \([$branch](#9D7CD8)\) ]($style)'
style = 'bold #7AA2F7'

[git_status]
conflicted = "|🤡 conflicted"
ahead = " ↑🎉 ahead"
behind = " ↓😡 behind"
diverged  = "|🤬 diverged"
# for space
modified  = "|🥹  modified"
staged    = "|😋 staged"
untracked = "|😅 untracked"
# stashed = "|🤓stashed"
renamed = "|🫣  renamed"
deleted = "|🤮 deleted"

format = '([$all_status$ahead_behind]($style)) '
style = "bold #9ECE6A"
