# vim:ft=kitty

## name:     Tokyo Night Kitty (Light)
## author:   Lawliet
## blurb:    Tokyo Night Day palette with blue, purple, and cyan accents

# The basic colors
foreground              #3760bf
background              #e1e2e7
selection_foreground    #3760bf
selection_background    #b7c1e3

# Cursor colors
cursor                  #82a1f1
cursor_text_color       #e1e2e7

# Scrollbar colors
scrollbar_handle_color  #a1a6c5
scrollbar_track_color   #c4c8da

# URL color when hovering with mouse
url_color               #007197

# Kitty window border colors
active_border_color     #2e7de9
inactive_border_color   #2e7de9
bell_border_color       #8c6c3e

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #e1e2e7
active_tab_background   #2e7de9
inactive_tab_foreground #3760bf
inactive_tab_background #c4c8da
tab_bar_background      #d7d9e0

# Colors for marks (marked text in the terminal)
mark1_foreground #e1e2e7
mark1_background #8c6c3e
mark2_foreground #e1e2e7
mark2_background #f52a65
mark3_foreground #e1e2e7
mark3_background #587539

# The 16 terminal colors

# black
color0 #a1a6c5
color8 #8990b3

# red
color1 #f52a65
color9 #f52a65

# green
color2  #587539
color10 #587539

# yellow
color3  #8c6c3e
color11 #8c6c3e

# blue
color4  #2e7de9
color12 #2e7de9

# magenta
color5  #9854f1
color13 #9854f1

# cyan
color6  #007197
color14 #007197

# white
color7  #6172b0
color15 #3760bf
