"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold #F7A8C4)$directory\
$git_branch\
$git_status\
\n[╰─ ](bold #F7A8C4)
"""

[directory]
format = "[ $path ]($style)"
style = "bold #FFB7C5"
truncation_length = 3
truncation_symbol = "…/"

#[git_branch]
#symbol = "TvT"
#format = '[$symbol \($branch\) ]($style)'
#style = 'cyan'

[git_branch]
symbol = "TvT"
format = '[[$symbol](#EC7FA9) \([$branch](#D45D8F)\) ]($style)'
style = 'bold #F4A7B9'

[git_status]
conflicted = "|🤡 conflicted"
ahead = " ↑🎉 ahead"
behind = " ↓😡 behind"
diverged  = "|🤬 diverged"
# for space
modified  = "|🥹  modified"
staged    = "|😋 staged"
untracked = "|😅 untracked"
# stashed = "|🤓stashed"
renamed = "|🫣  renamed"
deleted = "|🤮 deleted"

format = '([$all_status$ahead_behind]($style)) '
style = "bold #A7C7A2"
